### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by tbeu**
added Msgpack to required dependencies

My test on WinXP:
1. Clean install of python-2.7.6.msi
2. Install of setuptools-2.2.win32-py2.7.exe from http://www.lfd.uci.edu/~gohlke/pythonlibs/#setuptools
3. Try to run setup.py install -> Run into http://bugs.python.org/issue9291 -> Used workaround http://bugs.python.org/issue9291#msg206938
4. Try again to run setup.py install -> Run into issue http://stackoverflow.com/questions/20709641/cant-compile-msgpack-python-extension-under-windows -> Used workaround from http://www.borgelt.net/pycoco.html, i.e. typed
   SET VS90COMNTOOLS=%VS100COMNTOOLS%
   on cmd line to change compiler from VS2008 to VS2010.
5. Try again to run setup.py install -> Compilation succeeds (with warnings) and setup is finished

### CODE REVIEW

**Comment by tbeu** [comment]
It is probably easier to install msgpack from http://www.lfd.uci.edu/~gohlke/pythonlibs/#msgpack after step 2. Then users won't run into compilation issue of step 4.

**Comment by xogeny** [comment]
Thomas,

  I'm going to try including a pure Python version of msgpack and see if that helps.  I'll probably create a branch for that stuff.  Before going further down this path, I'd like to test that approach.  I'll let you know when I have something that you can try under Windows.

  Thanks for all your help.

**Comment by tbeu** [comment]
When compilation of step 4. failed the first time I actually observed that there is a pure Python fallback of msgpack. Nevertheless issue #37 can then still be reproduced with same error but different traceback.

**Comment by xogeny** [comment]
Thomas,

  Are you saying that you tried the Python only implementation and it still did not work?  I just wanted to be clear on this point.

  Thanks.

**Comment by tbeu** [comment]
Yes, the Python only fallback of msgpack also fails with fullRobot.mld. I did not test it with dsres.mld.

**Pull request merged**
